In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df_sbq = pd.read_csv("/content/drive/MyDrive/CodeML2023/sbq.csv").drop(["ID", "experience_key"], axis=1)

df_sbq

,time_interval_s,time_elapsed,TemperatureChamber_0_Celsius,TemperatureChamber_1_Celsius,TemperatureChamber_2_Celsius,TemperatureChamber_3_Celsius,TemperatureChamber_4_Celsius,TemperatureChamber_5_Celsius,TemperatureChamber_6_Celsius,TemperatureChamber_7_Celsius,...,C12_current_controller_5v5_detection_mA,C12_voltage_controller_3v3_pll_Volt,C12_voltage_controller_3v3_Volt,C12_voltage_controller_5v5_detection_Volt,total_time_elapsed_s,timestamp_start,C12_magnetometer_Bx,C12_magnetometer_By,C12_magnetometer_Bz,C12_magnetometer_Bnorm
0,3,3.495942,17.5325,17.6350,19.6925,15.4825,15.5300,20.6875,21.2100,20.6175,...,NaN,NaN,NaN,NaN,3.0000,1676581691,-2512471.250,1229968.125,-107012.3750,2799425.837
1,4,4.448050,17.3875,17.7575,19.9775,15.8825,15.4275,20.7000,20.9725,20.6175,...,NaN,NaN,NaN,NaN,4.0000,1676581692,-2515132.850,1229105.550,-107148.9281,2801441.522
2,5,5.424648,17.2725,17.8150,19.8125,15.4475,15.0275,20.4575,20.6225,20.6575,...,70.487808,3.272,3.344,5.528,5.0000,1676581693,-2512140.000,1230410.025,-106566.7906,2799305.751
3,6,6.427434,17.3425,17.6900,19.9150,15.4475,15.2400,20.4700,21.2600,20.6275,...,NaN,NaN,NaN,NaN,6.0000,1676581694,-2510852.850,1230520.400,-107043.1875,2798217.421
4,7,7.431471,17.2925,17.7600,19.7975,15.4800,15.3475,20.6300,20.8950,20.7775,...,NaN,NaN,NaN,NaN,7.0000,1676581695,-2510852.125,1230521.458,-107043.3789,2798217.243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169093,186751,3600.541400,17.8100,16.9100,17.0000,16.9100,16.9800,17.3300,19.5600,18.0900,...,NaN,NaN,NaN,NaN,186751.0559,1676768439,NaN,NaN,NaN,NaN
169094,186752,3601.620279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,186752.0099,1676768440,NaN,NaN,NaN,NaN
169095,186753,3602.652154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,186753.1539,1676768441,NaN,NaN,NaN,NaN
169096,186754,3603.468600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,70.292686,3.280,3.344,5.528,186754.0639,1676768442,NaN,NaN,NaN,NaN
169097,186755,3604.563779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,186755.0649,1676768443,NaN,NaN,NaN,NaN

In [ ]:
null_proportions = df_sbq.isnull().mean()
columns_to_drop = null_proportions[null_proportions > 0.7].index.tolist()

df_sbq = df_sbq.drop(columns=columns_to_drop)
df_sbq

,time_interval_s,time_elapsed,TemperatureChamber_0_Celsius,TemperatureChamber_1_Celsius,TemperatureChamber_2_Celsius,TemperatureChamber_3_Celsius,TemperatureChamber_4_Celsius,TemperatureChamber_5_Celsius,TemperatureChamber_6_Celsius,TemperatureChamber_7_Celsius,TemperatureChamber_8_Celsius,C12_temperature_diamond_Celsius,total_time_elapsed_s,timestamp_start,C12_magnetometer_Bx,C12_magnetometer_By,C12_magnetometer_Bz,C12_magnetometer_Bnorm
0,3,3.495942,17.5325,17.6350,19.6925,15.4825,15.5300,20.6875,21.2100,20.6175,21.0250,16.368673,3.0000,1676581691,-2512471.250,1229968.125,-107012.3750,2799425.837
1,4,4.448050,17.3875,17.7575,19.9775,15.8825,15.4275,20.7000,20.9725,20.6175,20.9250,13.935328,4.0000,1676581692,-2515132.850,1229105.550,-107148.9281,2801441.522
2,5,5.424648,17.2725,17.8150,19.8125,15.4475,15.0275,20.4575,20.6225,20.6575,21.3750,10.789278,5.0000,1676581693,-2512140.000,1230410.025,-106566.7906,2799305.751
3,6,6.427434,17.3425,17.6900,19.9150,15.4475,15.2400,20.4700,21.2600,20.6275,20.6225,10.522618,6.0000,1676581694,-2510852.850,1230520.400,-107043.1875,2798217.421
4,7,7.431471,17.2925,17.7600,19.7975,15.4800,15.3475,20.6300,20.8950,20.7775,20.8700,10.536246,7.0000,1676581695,-2510852.125,1230521.458,-107043.3789,2798217.243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169093,186751,3600.541400,17.8100,16.9100,17.0000,16.9100,16.9800,17.3300,19.5600,18.0900,18.3800,14.331684,186751.0559,1676768439,NaN,NaN,NaN,NaN
169094,186752,3601.620279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.335643,186752.0099,1676768440,NaN,NaN,NaN,NaN
169095,186753,3602.652154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.341279,186753.1539,1676768441,NaN,NaN,NaN,NaN
169096,186754,3603.468600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.343148,186754.0639,1676768442,NaN,NaN,NaN,NaN
169097,186755,3604.563779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.346731,186755.0649,1676768443,NaN,NaN,NaN,NaN

In [ ]:
df_sbq.dtypes

time_interval_s                      int64
time_elapsed                       float64
TemperatureChamber_0_Celsius       float64
TemperatureChamber_1_Celsius       float64
TemperatureChamber_2_Celsius       float64
TemperatureChamber_3_Celsius       float64
TemperatureChamber_4_Celsius       float64
TemperatureChamber_5_Celsius       float64
TemperatureChamber_6_Celsius       float64
TemperatureChamber_7_Celsius       float64
TemperatureChamber_8_Celsius       float64
C12_temperature_diamond_Celsius    float64
total_time_elapsed_s               float64
timestamp_start                      int64
C12_magnetometer_Bx                float64
C12_magnetometer_By                float64
C12_magnetometer_Bz                float64
C12_magnetometer_Bnorm             float64
dtype: object

In [ ]:
scaler = MinMaxScaler()

df_sbq[df_sbq.columns] = scaler.fit_transform(df_sbq[df_sbq.columns])

df_sbq

,time_interval_s,time_elapsed,TemperatureChamber_0_Celsius,TemperatureChamber_1_Celsius,TemperatureChamber_2_Celsius,TemperatureChamber_3_Celsius,TemperatureChamber_4_Celsius,TemperatureChamber_5_Celsius,TemperatureChamber_6_Celsius,TemperatureChamber_7_Celsius,TemperatureChamber_8_Celsius,C12_temperature_diamond_Celsius,total_time_elapsed_s,timestamp_start,C12_magnetometer_Bx,C12_magnetometer_By,C12_magnetometer_Bz,C12_magnetometer_Bnorm
0,0.000000,0.000000,0.232789,0.260096,0.453413,0.146045,0.144523,0.599013,0.661891,0.595729,0.605585,0.410188,0.000000,0.000000,0.420595,0.440860,0.098610,0.620169
1,0.000005,0.000263,0.221509,0.271275,0.485698,0.177924,0.136685,0.600658,0.627865,0.595729,0.590283,0.239452,0.000005,0.000005,0.000000,0.000000,0.000000,1.000000
2,0.000011,0.000533,0.212563,0.276523,0.467007,0.143256,0.106098,0.568750,0.577722,0.601520,0.659143,0.018710,0.000011,0.000011,0.472940,0.666714,0.420384,0.597540
3,0.000016,0.000811,0.218009,0.265115,0.478618,0.143256,0.122348,0.570395,0.669054,0.597177,0.543994,0.000000,0.000016,0.000016,0.676339,0.723126,0.076359,0.392458
4,0.000021,0.001088,0.214119,0.271504,0.465307,0.145846,0.130568,0.591447,0.616762,0.618893,0.581867,0.000956,0.000021,0.000021,0.676454,0.723667,0.076221,0.392425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169093,0.999979,0.994545,0.254376,0.193931,0.148400,0.259813,0.255400,0.157237,0.425501,0.229823,0.200842,0.267263,0.999979,0.999979,NaN,NaN,NaN,NaN
169094,0.999984,0.994843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.267541,0.999984,0.999984,NaN,NaN,NaN,NaN
169095,0.999989,0.995129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.267936,0.999990,0.999989,NaN,NaN,NaN,NaN
169096,0.999995,0.995354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.268067,0.999995,0.999995,NaN,NaN,NaN,NaN
169097,1.000000,0.995657,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.268319,1.000000,1.000000,NaN,NaN,NaN,NaN

In [ ]:
null_to_mean = ["TemperatureChamber_0_Celsius",
                "TemperatureChamber_1_Celsius",
                "TemperatureChamber_2_Celsius",
                "TemperatureChamber_3_Celsius",
                "TemperatureChamber_4_Celsius",
                "TemperatureChamber_5_Celsius",
                "TemperatureChamber_6_Celsius",
                "TemperatureChamber_7_Celsius",
                "TemperatureChamber_8_Celsius"]

column_mean = df_sbq[null_to_mean].mean()
df_sbq[null_to_mean] =df_sbq[null_to_mean].fillna(column_mean)

df_sbq

,time_interval_s,time_elapsed,TemperatureChamber_0_Celsius,TemperatureChamber_1_Celsius,TemperatureChamber_2_Celsius,TemperatureChamber_3_Celsius,TemperatureChamber_4_Celsius,TemperatureChamber_5_Celsius,TemperatureChamber_6_Celsius,TemperatureChamber_7_Celsius,TemperatureChamber_8_Celsius,C12_temperature_diamond_Celsius,total_time_elapsed_s,timestamp_start,C12_magnetometer_Bx,C12_magnetometer_By,C12_magnetometer_Bz,C12_magnetometer_Bnorm
0,0.000000,0.000000,0.232789,0.260096,0.453413,0.146045,0.144523,0.599013,0.661891,0.595729,0.605585,0.410188,0.000000,0.000000,0.420595,0.440860,0.098610,0.620169
1,0.000005,0.000263,0.221509,0.271275,0.485698,0.177924,0.136685,0.600658,0.627865,0.595729,0.590283,0.239452,0.000005,0.000005,0.000000,0.000000,0.000000,1.000000
2,0.000011,0.000533,0.212563,0.276523,0.467007,0.143256,0.106098,0.568750,0.577722,0.601520,0.659143,0.018710,0.000011,0.000011,0.472940,0.666714,0.420384,0.597540
3,0.000016,0.000811,0.218009,0.265115,0.478618,0.143256,0.122348,0.570395,0.669054,0.597177,0.543994,0.000000,0.000016,0.000016,0.676339,0.723126,0.076359,0.392458
4,0.000021,0.001088,0.214119,0.271504,0.465307,0.145846,0.130568,0.591447,0.616762,0.618893,0.581867,0.000956,0.000021,0.000021,0.676454,0.723667,0.076221,0.392425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169093,0.999979,0.994545,0.254376,0.193931,0.148400,0.259813,0.255400,0.157237,0.425501,0.229823,0.200842,0.267263,0.999979,0.999979,NaN,NaN,NaN,NaN
169094,0.999984,0.994843,0.414785,0.405636,0.414488,0.399996,0.394230,0.438172,0.453529,0.445757,0.443488,0.267541,0.999984,0.999984,NaN,NaN,NaN,NaN
169095,0.999989,0.995129,0.414785,0.405636,0.414488,0.399996,0.394230,0.438172,0.453529,0.445757,0.443488,0.267936,0.999990,0.999989,NaN,NaN,NaN,NaN
169096,0.999995,0.995354,0.414785,0.405636,0.414488,0.399996,0.394230,0.438172,0.453529,0.445757,0.443488,0.268067,0.999995,0.999995,NaN,NaN,NaN,NaN
169097,1.000000,0.995657,0.414785,0.405636,0.414488,0.399996,0.394230,0.438172,0.453529,0.445757,0.443488,0.268319,1.000000,1.000000,NaN,NaN,NaN,NaN

In [ ]:
df_result = df_sbq[df_sbq["C12_magnetometer_Bx"].isnull()]

df_train = df_sbq[df_sbq["C12_magnetometer_Bx"].isnull() == False]

X = df_train.drop(["C12_magnetometer_Bx", "C12_magnetometer_By", "C12_magnetometer_Bz", "C12_magnetometer_Bnorm"], axis=1)
y = df_train[["C12_magnetometer_Bx", "C12_magnetometer_By", "C12_magnetometer_Bz", "C12_magnetometer_Bnorm"]]

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
x_train.shape, y_train.shape, x_test.shape, y_train.shape

((106211, 14), (106211, 4), (26553, 14), (106211, 4))

In [ ]:
def calculate_smape(actual, predicted) -> float:

    if not all([isinstance(actual, np.ndarray),
                isinstance(predicted, np.ndarray)]):
        actual, predicted = np.array(actual), np.array(predicted)

    return round(
        np.mean(
            np.abs(predicted - actual) /
            ((np.abs(predicted) + np.abs(actual))/2)
        )*100, 2
    )

In [ ]:
# custom SMAPE loss
import tensorflow.keras.backend as K

def smape_loss(y_true, y_pred):
    epsilon = 0.1
    summ = K.maximum(K.abs(y_true) + K.abs(y_pred) + epsilon, 0.5 + epsilon)
    smape = K.abs(y_pred - y_true) / summ * 2.0
    return smape

In [ ]:
# keeping the norm

model3 = tf.keras.Sequential([
    #tf.keras.Input(shape=(10,)),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(4, activation="sigmoid")
])

model3.compile(loss=smape_loss,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              metrics=["mape"])

In [ ]:
model3.fit(x_train, y_train, epochs=10) # SMAPE loss

Epoch 1/10
3320/3320 [==============================] - 17s 5ms/step - loss: 0.0048 - mape: 4919.7134
Epoch 2/10
3320/3320 [==============================] - 18s 5ms/step - loss: 0.0048 - mape: 4912.7212
Epoch 3/10
3320/3320 [==============================] - 14s 4ms/step - loss: 0.0047 - mape: 4920.5190
Epoch 4/10
3320/3320 [==============================] - 17s 5ms/step - loss: 0.0046 - mape: 4911.6372
Epoch 5/10
3320/3320 [==============================] - 18s 6ms/step - loss: 0.0044 - mape: 4916.0723
Epoch 6/10
3320/3320 [==============================] - 15s 5ms/step - loss: 0.0044 - mape: 4916.7910
Epoch 7/10
3320/3320 [==============================] - 12s 3ms/step - loss: 0.0043 - mape: 4915.4961
Epoch 8/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0042 - mape: 4913.2524
Epoch 9/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0041 - mape: 4911.9819
Epoch 10/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0040 - mape: 4906.6724

In [ ]:
y_pred3 = model3.predict(x_test)

830/830 [==============================] - 1s 2ms/step

In [ ]:
calculate_smape(y_test, y_pred3)

0.61

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred3)

0.9615089823479748

In [ ]:
# keeping the norm

model4 = tf.keras.Sequential([
    #tf.keras.Input(shape=(10,)),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(4, activation="sigmoid")
])

model4.compile(loss=smape_loss,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              metrics=["mape"])

In [ ]:
model4.fit(x_train, y_train, epochs=10) # dropout

Epoch 1/10
3320/3320 [==============================] - 15s 4ms/step - loss: 0.0351 - mape: 5127.9023
Epoch 2/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0121 - mape: 4874.3882
Epoch 3/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0106 - mape: 4981.8052
Epoch 4/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0100 - mape: 4818.4985
Epoch 5/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0099 - mape: 4993.1294
Epoch 6/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0098 - mape: 4815.2622
Epoch 7/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0098 - mape: 4830.8491
Epoch 8/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0098 - mape: 4833.1333
Epoch 9/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0093 - mape: 4987.1768
Epoch 10/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0090 - mape: 4999.6035

In [ ]:
y_pred4 = model4.predict(x_test)

830/830 [==============================] - 2s 2ms/step

In [ ]:
smape4 = calculate_smape(y_test, y_pred4)
r2 = r2_score(y_test, y_pred4)

smape4, r2

(2.84, 0.8578394518732149)

In [ ]:
model5 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(4, activation="sigmoid")
])

model5.compile(loss=smape_loss,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              metrics=["mape"])

In [ ]:
model5.fit(x_train, y_train, epochs=10)

Epoch 1/10
3320/3320 [==============================] - 15s 4ms/step - loss: 0.0265 - mape: 4847.0337
Epoch 2/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0053 - mape: 4894.4292
Epoch 3/10
3320/3320 [==============================] - 15s 4ms/step - loss: 0.0046 - mape: 4905.6465
Epoch 4/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0043 - mape: 4899.1636
Epoch 5/10
3320/3320 [==============================] - 14s 4ms/step - loss: 0.0040 - mape: 4892.9756
Epoch 6/10
3320/3320 [==============================] - 14s 4ms/step - loss: 0.0039 - mape: 4875.2891
Epoch 7/10
3320/3320 [==============================] - 18s 5ms/step - loss: 0.0038 - mape: 4881.6362
Epoch 8/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0038 - mape: 4875.0078
Epoch 9/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0037 - mape: 4864.5405
Epoch 10/10
3320/3320 [==============================] - 16s 5ms/step - loss: 0.0037 - mape: 4875.7031

In [ ]:
y_pred5 = model5.predict(x_test)

830/830 [==============================] - 2s 2ms/step

In [ ]:
smape5 = calculate_smape(y_test, y_pred5)
r2 = r2_score(y_test, y_pred5)

smape5, r2

(0.57, 0.9628199138956489)

In [ ]:
df_orig = pd.read_csv("/content/drive/MyDrive/CodeML2023/sbq.csv")

In [ ]:
df_sbq_adjusted = df_orig.drop(["ID", "experience_key", "time_interval_s", "time_elapsed", "total_time_elapsed_s", "timestamp_start"], axis=1)

column_mean = df_sbq_adjusted[null_to_mean].mean()
df_sbq_adjusted[null_to_mean] = df_sbq_adjusted[null_to_mean].fillna(column_mean)

df_sbq_adjusted = df_sbq_adjusted.drop(columns=columns_to_drop)

df_sbq_adjusted[df_sbq_adjusted.columns] = scaler.fit_transform(df_sbq_adjusted[df_sbq_adjusted.columns])

df_sbq_adjusted

,TemperatureChamber_0_Celsius,TemperatureChamber_1_Celsius,TemperatureChamber_2_Celsius,TemperatureChamber_3_Celsius,TemperatureChamber_4_Celsius,TemperatureChamber_5_Celsius,TemperatureChamber_6_Celsius,TemperatureChamber_7_Celsius,TemperatureChamber_8_Celsius,C12_temperature_diamond_Celsius,C12_magnetometer_Bx,C12_magnetometer_By,C12_magnetometer_Bz,C12_magnetometer_Bnorm
0,0.232789,0.260096,0.453413,0.146045,0.144523,0.599013,0.661891,0.595729,0.605585,0.410188,0.420595,0.440860,0.098610,0.620169
1,0.221509,0.271275,0.485698,0.177924,0.136685,0.600658,0.627865,0.595729,0.590283,0.239452,0.000000,0.000000,0.000000,1.000000
2,0.212563,0.276523,0.467007,0.143256,0.106098,0.568750,0.577722,0.601520,0.659143,0.018710,0.472940,0.666714,0.420384,0.597540
3,0.218009,0.265115,0.478618,0.143256,0.122348,0.570395,0.669054,0.597177,0.543994,0.000000,0.676339,0.723126,0.076359,0.392458
4,0.214119,0.271504,0.465307,0.145846,0.130568,0.591447,0.616762,0.618893,0.581867,0.000956,0.676454,0.723667,0.076221,0.392425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169093,0.254376,0.193931,0.148400,0.259813,0.255400,0.157237,0.425501,0.229823,0.200842,0.267263,NaN,NaN,NaN,NaN
169094,0.414785,0.405636,0.414488,0.399996,0.394230,0.438172,0.453529,0.445757,0.443488,0.267541,NaN,NaN,NaN,NaN
169095,0.414785,0.405636,0.414488,0.399996,0.394230,0.438172,0.453529,0.445757,0.443488,0.267936,NaN,NaN,NaN,NaN
169096,0.414785,0.405636,0.414488,0.399996,0.394230,0.438172,0.453529,0.445757,0.443488,0.268067,NaN,NaN,NaN,NaN
169097,0.414785,0.405636,0.414488,0.399996,0.394230,0.438172,0.453529,0.445757,0.443488,0.268319,NaN,NaN,NaN,NaN

In [ ]:
df_adjusted_result = df_sbq[df_sbq["C12_magnetometer_Bx"].isnull()]

df_adjusted_train = df_sbq[df_sbq["C12_magnetometer_Bx"].isnull() == False]

X = df_adjusted_train.drop(["time_interval_s", "time_elapsed", "total_time_elapsed_s", "timestamp_start", "C12_magnetometer_Bx", "C12_magnetometer_By", "C12_magnetometer_Bz", "C12_magnetometer_Bnorm"], axis=1)
y = df_adjusted_train[["C12_magnetometer_Bx", "C12_magnetometer_By", "C12_magnetometer_Bz", "C12_magnetometer_Bnorm"]]

x_adjusted_train, x_adjusted_test, y_adjusted_train, y_adjusted_test = train_test_split(X, y, test_size=0.2, random_state=42)
x_adjusted_train.shape, y_adjusted_train.shape, x_adjusted_test.shape, y_adjusted_train.shape

((106211, 10), (106211, 4), (26553, 10), (106211, 4))

In [ ]:
y_adjusted_train

,C12_magnetometer_Bx,C12_magnetometer_By,C12_magnetometer_Bz,C12_magnetometer_Bnorm
41804,0.630149,0.812811,0.146268,0.455725
65093,0.632496,0.813092,0.155736,0.453166
16735,0.531495,0.968491,0.110895,0.586880
24969,0.626795,0.811927,0.133407,0.459299
109374,0.648326,0.795284,0.163759,0.433260
...,...,...,...,...
110268,0.647769,0.794296,0.167593,0.433658
119879,0.606200,0.866614,0.158972,0.489948
103694,0.526652,0.991771,0.154640,0.595400
131932,0.629849,0.822240,0.167613,0.457363
121958,0.567820,0.930938,0.158133,0.541453

In [ ]:
model6 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(4, activation="sigmoid")
])

model6.compile(loss=smape_loss,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              metrics=["mape"])

In [ ]:
model6.fit(x_adjusted_train, y_adjusted_train, epochs=10)

Epoch 1/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0130 - mape: 5028.3149
Epoch 2/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0127 - mape: 4999.0459
Epoch 3/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0124 - mape: 5000.5645
Epoch 4/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0122 - mape: 4995.5044
Epoch 5/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0120 - mape: 4984.9258
Epoch 6/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0118 - mape: 4981.4600
Epoch 7/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0114 - mape: 4961.4331
Epoch 8/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0111 - mape: 4965.4067
Epoch 9/10
3320/3320 [==============================] - 12s 4ms/step - loss: 0.0110 - mape: 4961.0796
Epoch 10/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0110 - mape: 4954.7471

In [ ]:
y_pred6 = model6.predict(x_adjusted_test)

830/830 [==============================] - 1s 2ms/step

In [ ]:
def calculate_metrics(test, pred):
  smape = calculate_smape(test, pred)
  r2 = r2_score(test, pred)
  return smape, r2

In [ ]:
calculate_metrics(y_adjusted_test, y_pred6)

(2.25, 0.8603895019501336)

In [ ]:
model7 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(4, activation="sigmoid")
])

model7.compile(loss=smape_loss,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              metrics=["mape"])

In [ ]:
model7.fit(x_adjusted_train, y_adjusted_train, epochs=10)

Epoch 1/10
3320/3320 [==============================] - 15s 5ms/step - loss: 0.0151 - mape: 5050.6987
Epoch 2/10
3320/3320 [==============================] - 14s 4ms/step - loss: 0.0125 - mape: 5044.8662
Epoch 3/10
3320/3320 [==============================] - 14s 4ms/step - loss: 0.0118 - mape: 5041.3828
Epoch 4/10
3320/3320 [==============================] - 22s 7ms/step - loss: 0.0116 - mape: 5017.0659
Epoch 5/10
3320/3320 [==============================] - 17s 5ms/step - loss: 0.0115 - mape: 5030.4653
Epoch 6/10
3320/3320 [==============================] - 14s 4ms/step - loss: 0.0113 - mape: 5009.4561
Epoch 7/10
3320/3320 [==============================] - 14s 4ms/step - loss: 0.0107 - mape: 5011.3911
Epoch 8/10
3320/3320 [==============================] - 15s 5ms/step - loss: 0.0105 - mape: 5017.7578
Epoch 9/10
3320/3320 [==============================] - 14s 4ms/step - loss: 0.0103 - mape: 5039.5112
Epoch 10/10
3320/3320 [==============================] - 13s 4ms/step - loss: 0.0102 - mape: 5057.5220

In [ ]:
y_pred7 = model7.predict(x_adjusted_test)

830/830 [==============================] - 1s 2ms/step

In [ ]:
calculate_metrics(y_adjusted_test, y_pred7)

(2.01, 0.8809647344788364)

## Decision Tree

In [ ]:
# from sklearn import tree
# model3 = tree.DecisionTreeRegressor()
# model3.fit(x_train,y_train)
# y_pred = model3.predict(x_test)

# mae = mean_absolute_error(y_test, y_pred)

# mse = mean_squared_error(y_test, y_pred)

# r2 = r2_score(y_test, y_pred)

# mae, mse, r2

In [ ]:
# y_result_pred =

df_orig = df_orig.drop(["C12_magnetometer_Bx", "C12_magnetometer_By", "C12_magnetometer_Bz", "C12_magnetometer_Bnorm"], axis=1)

model_data = {}

df_orig["C12_magnetometer_Bx"]=y_result_pred[:, 0]
df_orig["C12_magnetometer_By"]=y_result_pred[:, 1]
df_orig["C12_magnetometer_Bz"]=y_result_pred[:, 2]
df_orig["C12_magnetometer_Bnorm"]=y_result_pred[:, 3]

df_orig